name: axe-scan-dispatch
on:
  workflow_dispatch:
jobs:
  main-wf:
    name: main workflow to deploy code
    runs-on: ubuntu-20.04
    steps:
     - run: echo triggering job 
     - name: Repository Dispatch
       uses: peter-evans/repository-dispatch@v1
       with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mkathu/ul-witelabel-visual-test
          event-type: deploy
          client-payload: '{"environment": "https://publish-p34054-e124123.adobeaemcloud.com/","file-to-read":"magnum-urls"}'
