# This workflow is used to scan the whitelabel site for accesibility issues as part of CI/CD
name: axe-scan-whitelabel-sequential
on:
  #This workflow can be triggered as part of manual trigger or as a repository dispatch event with event name as "deploy"
  workflow_dispatch:
  repository_dispatch:
     types: [deploy]
     
     #Configured the scaning standard to be followed.
env:
  STANDARD_TO_CHECK: wcag2a,wcag2aa,wcga2aaa,wcag21a,wcag21aa,wcga21aaa
  #Below job does the following:
  # 1. Read the txt file with urls
  # 2. Scan the pages as per configured standards
  # 3. Archive the result
  # 4. Send slack notification
jobs:
  axe-core-scan-whitelabel:
    runs-on: ubuntu-latest
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - name: Read file with urls
        id: pickUrls
        run: echo ::set-output name=urls::$(cat .github/workflows/${{ github.event.client_payload.environment }}/${{ github.event.client_payload.file-to-read }}.txt) 
      - name: run axe scan on urls
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version
          npm install @axe-core/cli@4.3.2-alpha.209 -g
          axe ${{steps.pickUrls.outputs.urls}} --show-errors --load-delay=${{ github.event.client_payload.load-time }} --tags ${{env.STANDARD_TO_CHECK}} --save magnum-$(date +%Y%m%d%H%M).json
          
      - name: archive the result
        uses: actions/upload-artifact@v2 
        with:
          name: save-report
          path: /home/runner/work/ul-witelabel-visual-test/ul-witelabel-visual-test/*.json
     
  slack-notify:
    runs-on: ubuntu-latest
    needs:   axe-core-scan-whitelabel
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_CHANNEL: general
          SLACK_ICON: https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f9d1-200d-1f9af@2x.png
          SLACK_MESSAGE: Click on the ACTIONS URL to check the complete status and also to get the accessibility report. The reports is available as artifacts. 
          SLACK_TITLE: Accessibility report of Whitelabel site
          SLACK_USERNAME: mkathu
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
