name: axe-scan-whitelabel
on:
  workflow_dispatch:
jobs:
  read-json:
    runs-on: ubuntu-latest
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - name: Read .json with urls
        uses: juliangruber/read-file-action@v1
        id: budget
        with:
          path: .github/workflows/test-axe-core-url.json
    outputs:
          json_value: ${{toJSON(steps.budget.outputs.content)}}
  set-matrix: 
    runs-on: ubuntu-latest
    needs: read-json
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          echo ::set-output name=matrix-combinations::${{ needs.read-json.outputs.json_value }}
    outputs:
          matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}
          
  matrix-job:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix-combinations) }}
    continue-on-error: true
  
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - run: |
          npm install @axe-core/cli -g
          axe ${{matrix.url}} --load-delay=10000 --tags wcag21aaa --save magnum-$(date +%Y%m%d%H%M).json
      - name: archive the result
        uses: actions/upload-artifact@v2 
        with:
          name: magnum-$(date +%Y%m%d%H%M) report
          path: /home/runner/work/ul-witelabel-visual-test/ul-witelabel-visual-test/*.json
          
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_CHANNEL: general
          #SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f9d1-200d-1f9af@2x.png
          SLACK_MESSAGE: Click on the ACTIONS URL to check the complete status and also to get the accessibility report for page ${{matrix.url}}
          SLACK_TITLE: Accessibility report of Whitelabel site
          SLACK_USERNAME: mkathu
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
