name: axe-core scan for a page
on:
  workflow_dispatch:
jobs:
  axe-scan:
    name: axe-core-scan
    runs-on: ubuntu-latest
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - name: Read .json
        uses: juliangruber/read-file-action@v1
        id: budget
        with:
          path: .github/workflows/dev1/whitelabel-lighthouse-mobile.json
      - name: Echo json
        run: echo "::set-output name=value::${{ steps.budget.outputs.content }}"
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
    outputs:
      matrix: ${{ steps.budget.outputs.value }}
     
  job2:
    needs: axe-scan
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{needs.ace-scan.outputs.matrix}}
