name: Lighthouse-scan-ci
on: 
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Desktop Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
           https://www.magnumicecream.com/br/home.html
           https://www.magnumicecream.com/br/produtos.html
          configPath: '.github/workflows/lighthouse.json'
          budgetPath: .github/workflows/budget.json
          runs: 3
          temporaryPublicStorage: true
          
      - uses: actions/checkout@v2
      - name: Mobile Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        if: always()
        with:
          urls: |
           https://www.magnumicecream.com/br/home.html
           https://www.magnumicecream.com/br/produtos.html
          configPath: '.github/workflows/lighthouse-mobile.json'
          budgetPath: .github/workflows/mob-budget.json
          runs: 3
          temporaryPublicStorage: true
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://emoji.slack-edge.com/T23RE8G4F/lighthouse/5c41317b8ba846a5.png
          SLACK_MESSAGE: Click on the Actions url to check the point of failure and also to get the lighthouse report
          SLACK_TITLE: Lighthouse score
          SLACK_USERNAME: mkathu
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
