name: Lighthouse-scan
on: 
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: 'https://www.magnumicecream.com/br/home.html'
          configPath: './lighthouse.json'
