name: Lighthouse Check - foo
on:
  workflow_dispatch:
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://www.magnumicecream.com/br/home.html,https://www.magnumicecream.com/br/produtos.html,https://www.magnumicecream.com/br/produtos/classico.html,https://www.magnumicecream.com/br/p/cl%C3%A1ssico.html/07891075403215,https://www.magnumicecream.com/br/campaigns/magnum-amendoas-vegano.html,https://www.magnumicecream.com/br/artigos.html'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
