name: Lighthouse-scan
on: 
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
           https://www.magnumicecream.com/br/home.html
           https://www.magnumicecream.com/br/produtos.html
           https://www.magnumicecream.com/br/produtos/classico.html
           https://www.magnumicecream.com/br/p/cl%C3%A1ssico.html/07891075403215
           https://www.magnumicecream.com/br/campaigns/magnum-amendoas-vegano.html
           
           https://www.magnumicecream.com/br/artigos.html
          configPath: '.github/workflows/lighthouse.json'
          runs: 3
          temporaryPublicStorage: true
          
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: 'https://www.magnumicecream.com/br/home.html'
          configPath: '.github/workflows/lighthouse-mobile.json'
          runs: 3
          temporaryPublicStorage: true
