name: Lighthouse-scan
on: 
  workflow_dispatch:
  repository_dispatch:
     types: [lighthouse-test]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: '.github/workflows/${{ github.event.client_payload.brand }}.json'
          budgetPath: .github/workflows/budget.json
          temporaryPublicStorage: true
