name: magnum-axe-scan-whitelabel
on:
  workflow_dispatch:
env:
  STANDARD_TO_CHECK: wcag2a,wcag2aa,wcga2aaa,wcag21a,wcag21aa,wcga21aaa
  PAGE_LOAD_WAIT_TIME: 5000
  FILE_TO_READ: magnum-axe
  URLS: https://www.magnumicecream.com/br/home.html, https://www.magnumicecream.com/br/sitemap.html, https://www.magnumicecream.com/br/countryselector.html, https://www.magnumicecream.com/br/aboutus.html, https://www.magnumicecream.com/br/search.html, https://www.magnumicecream.com/br/campaigns/magnum-amendoas-vegano.html, https://www.magnumicecream.com/br/campaigns/magnum-pote.html, https://www.magnumicecream.com/br/campaigns/magnum-oversized-towels.html, https://www.magnumicecream.com/br/produtos.html, https://www.magnumicecream.com/br/produtos/classico.html, https://www.magnumicecream.com/br/produtos/mini-magnum.html, https://www.magnumicecream.com/br/produtos/mais-magnum.html, https://www.magnumicecream.com/br/terms-and-conditions.html, https://www.magnumicecream.com/br/tubs-carousel.html, https://www.magnumicecream.com/br/classics-carousel-new.html, https://www.magnumicecream.com/br/double-carousel-new.html, https://www.magnumicecream.com/br/secure/contato.html, https://www.magnumicecream.com/br/secure/signup.html, https://www.magnumicecream.com/br/secure/signup1.html, https://www.magnumicecream.com/br/preference-center.html, https://www.magnumicecream.com/br/preference-center/preference-optin.html, https://www.magnumicecream.com/br/preference-center/no-token.html, https://www.magnumicecream.com/br/perguntas-mais-frequentes.html, https://www.magnumicecream.com/br/SitespeedTestpage/launch-test.html, https://www.magnumicecream.com/br/painel.html, https://www.magnumicecream.com/br/artigos.html, https://www.magnumicecream.com/br/artigos/food.html, https://www.magnumicecream.com/br/artigos/food/bean-to-bite.html, https://www.magnumicecream.com/br/artigos/food/mindful-eating-alimentacao-equilibrada.html, https://www.magnumicecream.com/br/artigos/food/mindful-eating-comer-com-atencao-plena.html
jobs:
  read-json:
    runs-on: ubuntu-latest
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - name: Read .json with urls
        uses: juliangruber/read-file-action@v1
        id: budget
        with:
          path: .github/workflows/${{ secrets.ENVIRONMENT }}/${{env.FILE_TO_READ}}.json
    outputs:
          json_value: ${{toJSON(steps.budget.outputs.content)}}
          
  axe-scan-job:
    runs-on: ubuntu-latest
    needs: read-json
    continue-on-error: true
    steps:
      - name: setup npm
        uses: actions/checkout@v2
      - run: |
          npm install @axe-core/cli -g
          axe ${{env.URLS}} --load-delay=${{env.PAGE_LOAD_WAIT_TIME}} --tags ${{env.STANDARD_TO_CHECK}} --save magnum-$(date +%Y%m%d%H%M).json
      - name: archive the result
        uses: actions/upload-artifact@v2 
        with:
          name: save-report
          path: /home/runner/work/ul-witelabel-visual-test/ul-witelabel-visual-test/*.json
     
  slack-notify:
    runs-on: ubuntu-latest
    needs: axe-scan-job 
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_CHANNEL: general
          SLACK_ICON: https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f9d1-200d-1f9af@2x.png
          SLACK_MESSAGE: Click on the ACTIONS URL to check the complete status and also to get the accessibility report for page ${{matrix.url}}
          SLACK_TITLE: Accessibility report of Whitelabel site
          SLACK_USERNAME: mkathu
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
