name: Percy Cypress sequential tests
env:
        # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          #PERCY_TARGET_BRANCH: 'develop'
          PERCY_BRANCH: 'develop'
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
on:
  workflow_dispatch:
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: false
          record: true
          parallel: false
          spec: cypress/integration/${{ secrets.BRAND }}/*
          command-prefix: 'percy exec -- npx'
