name: Percy Cypress parallel tests
on:
  workflow_dispatch:
env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_TOTAL: -1
          PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
          #PERCY_TARGET_BRANCH: 'develop'
          PERCY_BRANCH: 'develop'
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
jobs:
  nonce:
    runs-on: ubuntu-latest
    # persist job results to other jobs in the workflow
    outputs:
      result: ${{ steps.nonce.outputs.result }}
    steps:
    # persist step results to other steps in the job
    - id: nonce
      # adding a timestamp makes the nonce more unique for re-runs
      run: echo "::set-output name=result::${{ github.run_id }}-$(date +%s)"
  cypress-run:
    name: Cypress run
    needs: nonce
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 2 copies of the current job in parallel
        containers: [1, 2]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: false
          record: true
          parallel: true
          group: 'unilever'
          command-prefix: 'percy exec -- npx'
    
       
  finalize-percy-build:
      name: finalize build
      needs: cypress-run
      runs-on: ubuntu-latest
      steps:
       - name: finalize
         uses: percy/exec-action@v0.3.1
         with:
           command: 'percy finalize --all'
         
