# This workflow builds the SDK using Java 11
name: Test Project Trigger tests

on:
  workflow_dispatch:
  
jobs:
  # Build and test the SDK
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Run tests via cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@60fb289d6e72261f095d7cefd578e659dd1b5182
          uses: indiesdev/curl@v1
          with:
          # The target url
            url: ""
            # The request method, basically one of GET, POST, PUT, PATCH
            method: ""
            # List of status codes to be accepted, else it is considerred to be failed
            accept: ""
            # Headers object
            headers: ""
            # Params object
            params: ""
            # Body object
            body: ""
            # timeout (millisec)
            timeout: ""
           # Basic authentication, format =>  username:password
            basic-auth: ""
            # Bearer Token
            bearer-token: ""
           # Proxy host, format =>  host:port
            proxy-url: ""
           # Proxy authentication, format =>  username:password
            proxy-auth: ""
           # show debug message of response
            is_debug: ""
           # custom config
            custom-config: ""
          env:
            TP_DEV_TOKEN: ${{ secrets.TP_DEV_TOKEN }}
            TP_AGENT_URL: http://localhost:8585
            TP_CLOUD_URL: ${{ secrets.TP_CLOUD_URL }}
