# This workflow builds the SDK using Java 11
name: Test Project Trigger tests

on:
  workflow_dispatch:
  
jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Run tests via cURL AxiosJS
          uses: indiesdev/curl@v1
          with:
          # The target url
            url: "https://api.testproject.io/v2/projects/MTEjcy3160WeNB2jYk4dUA/jobs/KXlll_Sr1EGh9mHnwFX-2w/run"
            # The request method, basically one of GET, POST, PUT, PATCH
            method: "POST"
            # List of status codes to be accepted, else it is considerred to be failed
            accept: ""
            # Headers object
            headers: "Authorization=Vu2hnTtrDxh5Y5GvyXKxWYPlzEdAHexnIvgtjdi6pOg1"
            # Params object
            params: ""
            # Body object
            body: '{"agentId": "","browsers": [],"queue": true,"restartDriver": false,"projectParameters": {},"testParameters": [],"tags": [],"capabilities": {}}'
