name: Whitelabel-Lighthouse-scan-ci
on: 
  workflow_dispatch:
jobs:
  whitelabel-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls for desktop
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: '.github/workflows/${{ secrets.ENVIRONMENT }}/whitelabel-lighthouse-desktop.json'
          budgetPath: .github/workflows/budget.json
          temporaryPublicStorage: true
          
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls for mobile
        uses: treosh/lighthouse-ci-action@v8
        if: always()
        with:
          configPath: '.github/workflows/${{ secrets.ENVIRONMENT }}/whitelabel-lighthouse-mobile.json'
          budgetPath: .github/workflows/mob-budget.json
          temporaryPublicStorage: true
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://emoji.slack-edge.com/T23RE8G4F/lighthouse/5c41317b8ba846a5.png
          SLACK_MESSAGE: Click on the ACTIONS URL to check the complete status and also to get the lighthouse report
          SLACK_TITLE: Lighthouse score of Whitelabel site
          SLACK_USERNAME: mkathu
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
